# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andrew Borg
email: andrew.b.borg@gmail.com
name: Andrew Borg
description: > # this means to ignore newlines until "baseurl:"
  Programmer, Designer, Developer
repostiroy: abborg/abborg.github.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://abborg.github.io" # the base hostname & protocol for your site
github_username:  abborg
github_avatar: "https://avatars2.githubusercontent.com/u/5313400"
linkedin_url: "https://www.linkedin.com/in/andrew-borg-0948017a"
strict_front_matter: true

permalink: /blog/:year/:month/:day/:title/

excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
highlights: rouge

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: my_categories
    values:
      layout: categories
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: tags
  -
    scope:
      path: "project"
    values:
      layout: project

collections:
  projects:
    output: true
    layout: post
    permalink: /projects/:title
  my_tags:
    output: true
    permalink: /tags/:name
  my_categories:
    output: true
    permalink: /categories/:name
